import React, { useState } from 'react';

const ACCESS_CODE = 'JUSTI2025';

export default function AccessCode({ onUnlock }) {
  const [code, setCode] = useState('');
    const [error, setError] = useState('');
      const [shake, setShake] = useState(false);

        const handleSubmit = (e) => {
            e.preventDefault();
                if (code.toUpperCase() === ACCESS_CODE) {
                      localStorage.setItem('justi_access', '1');
                            onUnlock();
                                } else {
                                      setError('Codigo incorreto. Tente novamente.');
                                            setShake(true);
                                                  setTimeout(() => setShake(false), 600);
                                                        setCode('');
                                                            }
                                                              };

                                                                return (
                                                                    <div style={{
                                                                          minHeight: '100vh',
                                                                                background: '#0B0F19',
                                                                                      display: 'flex',
                                                                                            flexDirection: 'column',
                                                                                                  alignItems: 'center',
                                                                                                        justifyContent: 'center',
                                                                                                              fontFamily: 'Inter, sans-serif',
                                                                                                                  }}>
                                                                                                                        <div style={{
                                                                                                                                background: '#111827',
                                                                                                                                        border: '1px solid rgba(255,107,0,0.3)',
                                                                                                                                                borderRadius: '16px',
                                                                                                                                                        padding: '48px 40px',
                                                                                                                                                                maxWidth: '420px',
                                                                                                                                                                        width: '90%',
                                                                                                                                                                                textAlign: 'center',
                                                                                                                                                                                        boxShadow: '0 0 40px rgba(255,107,0,0.1)',
                                                                                                                                                                                              }}>
                                                                                                                                                                                                      <div style={{ fontSize: '48px', marginBottom: '16px' }}>⚖️</div>
                                                                                                                                                                                                              <h1 style={{
                                                                                                                                                                                                                        color: '#FF6B00',
                                                                                                                                                                                                                                  fontSize: '28px',
                                                                                                                                                                                                                                            fontWeight: '800',
                                                                                                                                                                                                                                                      marginBottom: '8px',
                                                                                                                                                                                                                                                                letterSpacing: '-0.5px',
                                                                                                                                                                                                                                                                        }}>JUSTIFIKISI</h1>
                                                                                                                                                                                                                                                                                <p style={{
                                                                                                                                                                                                                                                                                          color: '#9CA3AF',
                                                                                                                                                                                                                                                                                                    fontSize: '14px',
                                                                                                                                                                                                                                                                                                              marginBottom: '32px',
                                                                                                                                                                                                                                                                                                                      }}>Plataforma de IA Juridica — Acesso Restrito</p>

                                                                                                                                                                                                                                                                                                                              <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                        <div style={{ marginBottom: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                value={code}
                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => { setCode(e.target.value); setError(''); }}
                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Digite o codigo de acesso"
                                                                                                                                                                                                                                                                                                                                                                                                                          maxLength={20}
                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: '14px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: '#1F2937',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: error ? '2px solid #ef4444' : '2px solid rgba(255,107,0,0.3)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#F3F4F6',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        letterSpacing: '4px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textTransform: 'uppercase',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        outline: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        boxSizing: 'border-box',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animation: shake ? 'shake 0.3s ease-in-out' : 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    autoFocus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#ef4444',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: '13px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: '-8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: 'linear-gradient(135deg, #FF6B00, #CC5500)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '700',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: '1px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition: 'opacity 0.2s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onMouseOver={(e) => e.target.style.opacity = '0.85'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onMouseOut={(e) => e.target.style.opacity = '1'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ENTRAR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#4B5563',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: '24px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>Acesso apenas para usuarios autorizados</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @keyframes shake {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0%, 100% { transform: translateX(0); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            25% { transform: translateX(-8px); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      75% { transform: translateX(8px); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }